### ISSUE TITLE
Nothing displayed and errors with zsh

### ISSUE THREAD

**Issue by tlg-tg** [AymanLyesri/hyprland-conf#28]
There is nothing except blank on display in terminal there are errors
![image](https://github.com/user-attachments/assets/009357d0-655b-4bf6-9c17-1cd73416a092)

**Comment by MacaylaMarvelous81** [comment]
You're missing packages; see the error output. For example, you don't have `starship` or `fastfetch`.

**Comment by MacaylaMarvelous81** [comment]
I remember having that issue but I don't exactly remember how I solved it. The hyprland configuration may have errors and you may be still missing things. Do you have bun? It might also help you find errors if you check the output when you run Hyprland in the terminal emulator or check its logs.

**Comment by AymanLyesri** [comment]
did u follow the installation guide perhaps? see [here](https://github.com/AymanLyesri/hyprland-conf?tab=readme-ov-file#installation-guide)
1. clone the repository
2. run the install script (last commit) --> it will install all the packages (eg: starship, fastfetch etc...)

**Comment by AymanLyesri** [comment]
if u followed the installation and got errors let me know am happy to help

**Comment by tlg-tg** [comment]
I did follow the steps and it did not work

**Comment by tlg-tg** [comment]
Here is the output after runnung the script
![image](https://github.com/user-attachments/assets/0d1940ef-28ca-4520-9611-bbf3c3d5c49c)

**Comment by tlg-tg** [comment]
Here is how it looks after reboot
![image](https://github.com/user-attachments/assets/b71eb2fe-e8fb-45f2-a3d0-520069be8e8a)

**Comment by tlg-tg** [comment]
Ok so the script does not install almost any of the packages and ags just does not want to get installed there is also a missing dir .cache/wal/sequences

**Comment by tlg-tg** [comment]
``(com.github.Aylur.ags:9974): Gjs-CRITICAL **: 21:19:07.498: JS ERROR: TypeError: section.get_file() is null
applyCss/<@resource:///com/github/Aylur/ags/app.js:73:34
applyCss@resource:///com/github/Aylur/ags/app.js:81:29
refreshCss@file:///tmp/ags/main.js:1844:7
@file:///tmp/ags/main.js:1884:1
async*_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34


(com.github.Aylur.ags:9974): Gjs-Console-CRITICAL **: 21:19:07.499: Gtk.CssProviderError: <data>:1:0Expected a valid selector
applyCss@resource:///com/github/Aylur/ags/app.js:81:29
refreshCss@file:///tmp/ags/main.js:1844:7
@file:///tmp/ags/main.js:1884:1
`async*_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34`

this is the error thrown by ags

**Comment by tlg-tg** [comment]
got it working kind but still no wallpaper works for some reason could be that there is not a wallpaper setter program installed. Which one is supposed to be installed?

**Comment by AymanLyesri** [comment]
> Ok so the script does not install almost any of the packages and ags just does not want to get installed there is also a missing dir .cache/wal/sequences

these sequences get generated each time the wallpaper changes when switching workspaces, make sure that hyprpaper and its scripts are working if not let me know

**Comment by AymanLyesri** [comment]
> got it working kind but still no wallpaper works for some reason could be that there is not a wallpaper setter program installed. Which one is supposed to be installed?

its `hyprpaper`
to test it:
run hyprpaper in terminal
then in a new terminal run : $HOME/.config/hypr/hyprpaper/load.sh

**Comment by tlg-tg** [comment]
Ok so it worked after I copied the wallpapers dir to /home/myuser but the ags wallpaper selector does not work

**Comment by AymanLyesri** [comment]
> Ok so it worked after I copied the wallpapers dir to /home/myuser but the ags wallpaper selector does not work

the latest version of the dotfiles stores wallpapers in /home/myuser/.config/wallpapers so u are following an old version,

I've made a one line command u could just paste in ur terminal:
```
bash -c "$(curl -fsSL https://raw.githubusercontent.com/AymanLyesri/hyprland-conf/refs/heads/master/.config/hypr/maintenance/INSTALL.sh)"
```
this will install everything, its been tested in a virtual machine so its guaranteed to work

**Comment by tlg-tg** [comment]
ok I used the command one problem that is still is that the wallpaper selector in ags is not working 
I select any wallpaper and then nothing happens

**Comment by AymanLyesri** [comment]
screenshots please, the more the better, oh btw u need a reboot after finishing the install using the one liner

**Comment by tlg-tg** [comment]
yes I did reboot

**Comment by tlg-tg** [comment]
![Uploading 2024-10-12-221740_hyprshot.png…]()

**Comment by tlg-tg** [comment]
![2024-10-12-221740_hyprshot](https://github.com/user-attachments/assets/73dc1eb7-7b4d-48a2-b193-fb3adab10a37)

**Comment by AymanLyesri** [comment]
When u click on one of the wallpapers a revealer should display at the bottom like so:
![image](https://github.com/user-attachments/assets/4512db7b-bafd-4a0b-b019-22e6e98ca68f)

**Comment by tlg-tg** [comment]
yes that it does and after I click on the lower image nothing happens

**Comment by AymanLyesri** [comment]
Click on the reset button
![image](https://github.com/user-attachments/assets/6593aedb-ecbc-479b-9e04-3a633f1b15b7)
then do : `SUPER + b` to restart ags

**Comment by tlg-tg** [comment]
did that and nothing changes

**Comment by AymanLyesri** [comment]
in a new terminal do : 
```
killall hyprpaper; hyprpaper
```
then click the reset button in wallpaper selector

if it dosent work, show me the output of 
``` 
cat $HOME/.config/hypr/hyprpaper/config/defaults.conf 
```

**Comment by tlg-tg** [comment]
│ File: /home/tlg/.config/hypr/hyprpaper/config/defaults.conf
───────┼────────────────────────────────────────────────────────────────────────────────────────────────
   1 ~ │ w-1=$HOME/.config/wallpapers/normal/__ayanami_rei_neon_genesis_evangelion_and_2_more_drawn_by_s
       │ wkl_d__733a176b4dbed9c6f859924dfebb73f2.jpg
   2 ~ │ w-2=$HOME/.config/wallpapers/normal/__ayanami_rei_neon_genesis_evangelion_and_2_more_drawn_by_s
       │ wkl_d__733a176b4dbed9c6f859924dfebb73f2.jpg
   3 ~ │ w-3=$HOME/.config/wallpapers/normal/__airi_kanna_stellive_drawn_by_cicei__8207191a8e0c0d6d32016
       │ 8a23bba15da.png
   4 ~ │ w-4=$HOME/.config/wallpapers/normal/__hoshimachi_suisei_hololive_drawn_by_fuann__9238bd873fcf2d
       │ bfb59133fb4dae6cd4.jpg
   5 ~ │ w-5=$HOME/.config/wallpapers/normal/__herta_honkai_and_1_more_drawn_by_apple_caramel__3ed780454
       │ ec4e598c89e2b9920bc5c1c.jpg
   6 ~ │ w-6=$HOME/.config/wallpapers/normal/__kazusa_blue_archive_drawn_by_uaxa2334__82e1237f9fc8f67adc
       │ e6dc48061d54ad.jpg
   7 ~ │ w-7=$HOME/.config/wallpapers/normal/__kisaki_blue_archive_drawn_by_aoi_sakura_seak5545__f6c90df
       │ 1f7da64b7591db4b59edd0657.jpg
   8 ~ │ w-8=$HOME/.config/wallpapers/normal/__kita_ikuyo_bocchi_the_rock_drawn_by_bafangyu__d72eb163096
       │ c2eb4a544d362ed6603d8.jpg
   9 ~ │ w-9=$HOME/.config/wallpapers/normal/__shyrei_faolan_pepe_the_frog_vedal987_filian_and_rick_astl
       │ ey_indie_virtual_youtuber_drawn_by_haedgie__19ca44fa28b99f7fcc265fa76a7840b5.jpg
  10 ~ │ w-10=$HOME/.config/wallpapers/normal/__lumine_genshin_impact_drawn_by_heitian_keji__1f3aebacc1e
       │ f15d910b1c0b3619d9b22.jpg

**Comment by tlg-tg** [comment]
could it be an issue with set-wallpaper.sh? Here is the file
`
#!/bin/bash
hyprDir=$HOME/.config/hypr                                 # hypr directory
current_config=$hyprDir/hyprpaper/config/defaults.conf           # config file
previous_config=$hyprDir/hyprpaper/config/previous.conf          # previous config file
current_workspace=$(hyprctl monitors | grep active | awk '{print $3}') # get current workspace

new_wallpaper=""

#############################################

if [ -z "$1" ]; then
    echo "Usage: set-wallpaper.sh <workspace_id>"
    workspace_id=$current_workspace
else
    echo "Setting random wallpaper for workspace $1"
    workspace_id=$1
fi

# check for $2
if [ -z "$2" ]; then
    echo "Setting random wallpaper for workspace $workspace_id"
    new_wallpaper=$(find $HOME/wallpapers/normal -type f | shuf -n 1 | sed "s|$HOME|\\\$HOME|") # get random wallpaper
else
    echo "Setting wallpaper $2 for workspace $workspace_id"
    new_wallpaper=$(echo $2 | sed "s|$HOME|\\\$HOME|") # get wallpaper
fi

#############################################

old_wallpaper=$(grep "w-${workspace_id}" $current_config | cut -d'=' -f2)

#check if wallpaper is the same
if [ "$old_wallpaper" = "$new_wallpaper" ]; then
    echo "Wallpaper is already set to $new_wallpaper"
    exit 0
fi

hyprctl hyprpaper preload "$new_wallpaper" # preload wallpaper

hyprctl hyprpaper unload "$old_wallpaper" # unload old wallpaper

#############################################

if [ "$workspace_id" = "$current_workspace" ]; then
    $hyprDir/hyprpaper/w.sh "$new_wallpaper" & # set wallpaper
fi

#############################################

sed -i "s|w-${workspace_id}=.*|w-${workspace_id}=${old_wallpaper}|" $previous_config # set wallpaper in previous config

sed -i "s|w-${workspace_id}=.*|w-${workspace_id}=${new_wallpaper}|" $current_config # set wallpaper in config

`

**Comment by AymanLyesri** [comment]
> ![2024-10-12-221740_hyprshot](https://private-user-images.githubusercontent.com/61950743/375985184-73dc1eb7-7b4d-48a2-b193-fb3adab10a37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NjU3MTgsIm5iZiI6MTcyODc2NTQxOCwicGF0aCI6Ii82MTk1MDc0My8zNzU5ODUxODQtNzNkYzFlYjctN2I0ZC00OGEyLWIxOTMtZmIzYWRhYjEwYTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDIwMzY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNjgxMjgxOWQzN2EzOTNmNjZiYTgzOTFjODVlZDc4NDZlNjllN2FhYjc2MmNmMzA5ZDM0Mjc0ZTkwMzMxYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3Xlvim51GAvXby7nlX9NjEXivYkQ2RzMXL3CT8AvMsE)

hmmm, i see u have different wallpapers, how did u changed them, is it from the wallpaper selector or from the config files

**Comment by tlg-tg** [comment]
from the wallpaper selector

**Comment by AymanLyesri** [comment]
so it worked before pheeww, good, now do in a new terminal
```
git restore .
git fetch --all
git reset --hard origin/master
reboot
```

**Comment by tlg-tg** [comment]
Now it does not display any wallpaper

**Comment by tlg-tg** [comment]
so the wallpaper switcher still is not working

**Comment by tlg-tg** [comment]
but when I run ./set-wallpaper.sh manualy trough cli it does work

**Comment by AymanLyesri** [comment]
i fixed a bug when switching to the same wallpaper twice, i don't if that was the problem for u
do a `git pull` and let me know

**Comment by tlg-tg** [comment]
ok did git pull still the same interesting could it be in set-wallpaper.sh problem?

**Comment by tlg-tg** [comment]
ok so now I rebooted and logged in and there is no wallpaper at all also tried to use wallpaper select and does nothing do I have to chose a specific number from the wallpapers?

**Comment by AymanLyesri** [comment]
Idk, it works for both my laptop, desktop and virtual machine, we need somebody else to confirm if this is a problem with the script or with ur config/machine

**Comment by tlg-tg** [comment]
I do see that in set-wallpaper.sh on line 22 $(find $HOME/wallpapers/normal instead of /.config/wallpapers could it be that?

**Comment by AymanLyesri** [comment]
Oh, I missed it, I've made a hotfix.
`git pull` as always
But don't get ur hopes up it only affects random wallpaper generation, which is not ur case with the wallpaper selector

**Comment by tlg-tg** [comment]
yeah I know just trying to help and maybe figure out the problem

**Comment by tlg-tg** [comment]
I see that every time I reboot and log in there is no wallpaper until I run ./set-wallpaper.sh very interesting

**Comment by AymanLyesri** [comment]
Hmmm maybe the problem is in the boot up scripts, I'll check it out tomorrow and let u know
BTW I really appreciate ur feedback it means a lot

**Comment by tlg-tg** [comment]
Yeah no problem I love the work and trying to work on a fix too and improvements

**Comment by tlg-tg** [comment]
Also thanks for all the help

**Comment by AymanLyesri** [comment]
![image](https://github.com/user-attachments/assets/75b31d7c-6af5-4c16-9816-1941098969f8)
this is the script that get executed at the beginning after hyprpaper
```
$HOME/.config/hypr/hyprpaper/load.sh
```
run it and see if there are any errors

**Comment by tlg-tg** [comment]
ok I just ran the script and everything shows ok

**Comment by tlg-tg** [comment]
oh and the new get-waifyu.py is not working as much as I tried

**Comment by tlg-tg** [comment]
Right now I am trying to install the rice onto my laptop to see if it works correctly trough the one line script will let you know

**Comment by tlg-tg** [comment]
so the one line script is not working for some reason like curl says there is error 404

**Comment by tlg-tg** [comment]
ok got it to work was a problem on my side

**Comment by tlg-tg** [comment]
ok after reboot the script does still not install any of the packages

**Comment by AymanLyesri** [comment]
> ok after reboot the script does still not install any of the packages

it should install all the packages before reboot not after
run the install script and show me if there are any errors

**Comment by tlg-tg** [comment]
Ok so I figured out that there is a problem in your pkglist for pacman since new blueman is depricated or corrupted you have to use blueman-git

**Comment by AymanLyesri** [comment]
> Ok so I figured out that there is a problem in your pkglist for pacman since new blueman is depricated or corrupted you have to use blueman-git

I'll push a hotfix right now

**Comment by tlg-tg** [comment]
Yes that was the whole problem for the script that blueman failed which basically made it so that no packages were installed and also the configuration fully works on laptop no problems so I guess it is my desktop machine problem that it does not work

**Comment by AymanLyesri** [comment]
> I'll push a hotfix right now

done

> Yes that was the whole problem for the script that blueman failed which basically made it so that no packages were installed and also the configuration fully works on laptop no problems so I guess it is my desktop machine problem that it does not work

glad it worked in ur laptop, try a clean arch install in ur desktop that would solve the problem

**Comment by tlg-tg** [comment]
yeah will do

**Comment by AymanLyesri** [comment]
So i guess this is solved,
if u have any other issue or suggestion lemme know

**Comment by tlg-tg** [comment]
yes and thank you for all the help

**Comment by tlg-tg** [comment]
So just tried to install the dots on my main desktop again and still no wallpaper but this time load.sh shows this.

❯ ❯ $HOME/.config/hypr/hyprpaper/load.sh
cp: cannot stat '/home/tlg/.config/wallpapers/custom/*': No such file or directory
cp: target '/usr/share/backgrounds': No such file or directory
Couldn't connect to /run/user/1000/hypr/882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff_1739653152_2039431911/.hyprpaper.sock. (3)
Couldn't connect to /run/user/1000/hypr/882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff_1739653152_2039431911/.hyprpaper.sock. (3)
Couldn't connect to /run/user/1000/hypr/882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff_1739653152_2039431911/.hyprpaper.sock. (3)
Couldn't connect to /run/user/1000/hypr/882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff_1739653152_2039431911/.hyprpaper.sock. (3)
Couldn't connect to /run/user/1000/hypr/882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff_1739653152_2039431911/.hyprpaper.sock. (3)
Couldn't connect to /run/user/1000/hypr/882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff_1739653152_2039431911/.hyprpaper.sock. (3)
Couldn't connect to /run/user/1000/hypr/882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff_1739653152_2039431911/.hyprpaper.sock. (3)
Couldn't connect to /run/user/1000/hypr/882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff_1739653152_2039431911/.hyprpaper.sock. (3)
Couldn't connect to /run/user/1000/hypr/882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff_1739653152_2039431911/.hyprpaper.sock. (3)
Couldn't connect to /run/user/1000/hypr/882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff_1739653152_2039431911/.hyprpaper.sock. (3)

**Comment by tlg-tg** [comment]
Made the directory /usr/share/backgrounds and now it shows this

❯ $HOME/.config/hypr/hyprpaper/load.sh
cp: cannot stat '/home/tlg/.config/wallpapers/custom/*': No such file or directory
cp: cannot create regular file '/usr/share/backgrounds/__albion_azur_lane_drawn_by_uaxa2334__000fdfe75113f2144a50b3705161f5d2.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__burnice_white_luciana_de_montefio_and_piper_wheel_zenless_zone_zero_drawn_by_hakusama233__5125aa4e807eea5df772929b2f1cd401.png': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__changli_wuthering_waves_drawn_by_uaxa2334__b4fe81b5f2b51aaea811eefeb85c5491.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__dehya_genshin_impact_drawn_by_xude__bc66c4b2ab9ac2c0e4c62cb0e59e0cd0.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__emilie_genshin_impact_drawn_by_guaishengyin__d130af022d8a4a4f2d4ed05d32e7ca8c.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__eula_genshin_impact_drawn_by_swkl_d__d2420848139db9f4c2b6b1e061920dbe.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__eula_genshin_impact_drawn_by_the_what_sa__b9eed010d87021b424f633d0c1f920e3.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__feixiao_and_flying_aureus_honkai_and_1_more_drawn_by_swkl_d__5e0d01fc5e555f50bf0bba9a58500afc.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__han_juri_street_fighter_and_1_more_drawn_by_bokkusu__ccaedcdf426899516dad5b8247bf6f62.png': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__herta_honkai_and_1_more_drawn_by_apple_caramel__3ed780454ec4e598c89e2b9920bc5c1c.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__iori_and_iori_blue_archive_drawn_by_dizzen__7c56e7e702806ceaac863b9b0d210b17.png': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__ishtar_fate_and_1_more_drawn_by_z3zz4__86351a4af472216f09b931a5d1dbca3a.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__kamisato_ayaka_and_shenhe_genshin_impact_drawn_by_swkl_d__99dd0704eabf5d700f3e3d05f45a9300.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__kazusa_blue_archive_drawn_by_uaxa2334__82e1237f9fc8f67adce6dc48061d54ad.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__kisaki_blue_archive_drawn_by_aoi_sakura_seak5545__f6c90df1f7da64b7591db4b59edd0657.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__kisaki_blue_archive_drawn_by_chen_bingyou__6c83c49df1027e034b7ef3f0f73235a7.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__kisaki_blue_archive_drawn_by_mile_miluo__af4b455fc2341b75c3ad4dc022305bdf.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__kita_ikuyo_bocchi_the_rock_drawn_by_bafangyu__d72eb163096c2eb4a544d362ed6603d8.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__lingsha_honkai_and_1_more_drawn_by_kuroduki_pieat__c38e0ed2ccc09c02db2a8245bc036762.png': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__lumine_genshin_impact_drawn_by_heitian_keji__1f3aebacc1ef15d910b1c0b3619d9b22.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__m200_girls_frontline_drawn_by_bluebeel2__b4b6630084133e043246652277cbab33.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__mika_blue_archive_drawn_by_uaxa2334__333b1cb5b965bfc6094ed6e9162dfc95.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__ningguang_and_ningguang_genshin_impact_drawn_by_w_q_y__28169aa1d42203051a2cf3b9e58dbbf0.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__original_drawn_by_anata_no_utahime_lzr13708949567__3c338d5a9971ba1b80f4046dfc751718.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__original_drawn_by_datan_uu__3cc582513dcff139a485b2c793736c44.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__original_drawn_by_hani_haya__26520fbc59205afd446bf7f7dd0b0d19.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__original_drawn_by_hani_haya__467724769eb3e8ec28712cc5c3e571c3.png': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__original_drawn_by_mac_star__3e313866d6435f61f819d1d6123ab981.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__original_drawn_by_neko_blow__cb1428b3668734320c6362330b403c80.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__original_drawn_by_ping9137__e5fc9c7c37bb19008006759aea886e39.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__original_drawn_by_proxyl__2c6f048f4e1786ccb7941d5367b9fcaf.png': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__original_drawn_by_ribao__398db021670fbf4ca9b6843fef5171e9.png': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__original_drawn_by_swkl_d__7b333431520df7632406ad70186671eb.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__original_drawn_by_tu_er_tm__1b1fabdc9969afff10e57a00bd8be84e.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__original_drawn_by_tuweibu__41ae2e99e1d5e2443d7582b83e05ef48.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__original_drawn_by_vikiye__59e227bae545a3074f8fb4128065a4d4.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__original_drawn_by_zzzi_gn__c4c677bda1f9b7d579ccc1c1ba3f95ad.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__rebecca_lucy_and_dorio_cyberpunk_and_1_more_drawn_by_feguimel__0d026f4ad56695ddb81e31f54337ea7a.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__robin_honkai_and_1_more_drawn_by_swkl_d__72aeec3f718f00424689c5124f13563f.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__shyrei_faolan_pepe_the_frog_vedal987_filian_and_rick_astley_indie_virtual_youtuber_drawn_by_haedgie__19ca44fa28b99f7fcc265fa76a7840b5.jpg': Permission denied
cp: cannot create regular file '/usr/share/backgrounds/__xingtong_qq_dance_drawn_by_pugongying__1df62f1c8177c9d2d56c8889f37559de.jpg': Permission denied
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
