### ISSUE TITLE
Sometimes unhovering the bar while unpinned does not hide it

### ISSUE THREAD

**Issue by MacaylaMarvelous81** [AymanLyesri/hyprland-conf#29]
If you move the cursor too fast, hover effects may not occur. For example, the top bar may not hide or show itself, and the Spotify panel may not hide itself.

**Comment by AymanLyesri** [comment]
Its fixed now, lemme if u have any other suggestions

**Comment by MacaylaMarvelous81** [comment]
Nice work, but the bar still doesn't hide itself consistently. I've noticed that it works a lot better when I have no windows nearby it, like when I have no windows or when in a workspace with gapsout. I'm not familiar with GDK or AGS, but I believe the `hover-lost` isn't getting emitted because my cursor causes another window to focus instead of the AGS window--that's what I gathered from [this message](https://github.com/Aylur/ags/issues/351#issuecomment-1994375843).

If I do use `leave-notify-event` as suggested in that message the bar does hide itself consistently, but unfortunately hovering over any elements of the bar fires the event making the bar useless.

**Comment by MacaylaMarvelous81** [comment]
@AymanLyesri did you see this?

**Comment by AymanLyesri** [comment]
> Nice work, the media player works great now! Unfortunately, the bar still doesn't hide itself consistently. I've noticed that it works a lot better when I have no windows nearby it, like when I have no windows or when in a workspace with gapsout. I'm not familiar with GDK or AGS, but I believe the `hover-lost` isn't getting emitted because my cursor causes another window to focus instead of the AGS window--that's what I gathered from [this message](https://github.com/Aylur/ags/issues/351#issuecomment-1994375843).
> 
> If I do use `leave-notify-event` as suggested in that message the bar does hide itself consistently, but unfortunately hovering over any elements of the bar fires the event making the bar useless.

i made the work around like what Aylur suggested will be added in the next update

> @AymanLyesri did you see this?

I don't normally check closed issues, but u could reopen them if the issues persist

**Comment by MacaylaMarvelous81** [comment]
Yeah I can’t reopen the issue if I wasn’t the one who closed it

**Comment by AymanLyesri** [comment]
The hover-lost works fine in my desktop, but it sometimes skips in a Virtual-Machine, maybe its a performance issue
I've made some tweaks to improve the performance
after updating, do 
```
rm -rf .cache/ags/notifications
```
and then restart ags : `SUPER + b`

**Comment by MacaylaMarvelous81** [comment]
I updated but it still doesn't hide sometimes. I think it may be because I use I high mouse DPI. I can try recording a video later.

**Comment by AymanLyesri** [comment]
Try that, and make sure to update before doing so.

**Comment by MacaylaMarvelous81** [comment]
https://github.com/user-attachments/assets/79553979-5712-4e7d-b08f-74d42062dce2

**Comment by AymanLyesri** [comment]
The only solution that kinda "works" is increasing the bar's padding, but this takes up more screen space than necessary.
**original**
![image](https://github.com/user-attachments/assets/0c9e5ac1-b604-482f-930c-6cbfcd145846)
**fix**
![image](https://github.com/user-attachments/assets/30236137-0ad4-4c89-bc8f-4bcc2d57ec43)

**Comment by MacaylaMarvelous81** [comment]
I found that `on_hover_lost` is based on `leave-notify-event`:
```js
this.connect('leave-notify-event', (_, event: Gdk.Event) => {
    if (!this.isHovered(event)) {
        this.unset_state_flags(Gtk.StateFlags.PRELIGHT);
        return this.on_hover_lost?.(this, event);
    }
});
```
[eventbox.ts:75-80](https://github.com/Aylur/ags/blob/60180a184cfb32b61a1d871c058b31a3b9b0743d/src/widgets/eventbox.ts#L75-L80)
I tried using `get_pointer` and comparing its y value to the height of the bar like `isHovered` but sometimes when the cursor moves too fast it looks like the cursor's y position is low. I'm not sure why.

I thought maybe I could ignore the event for `GDK_NOTIFY_INFERIOR` and `GDK_NOTIFY_ANCESTOR` details in [Gdk.EventCrossing](https://docs.gtk.org/gdk3/struct.EventCrossing.html) but I can't figure out how to do that in JS. By `console.log`ging the event object I get an empty `Gdk.Event {}`. I can call methods on it but I can't figure out how to get the details property with the `Gdk.Event` union since it doesn't look like I can use properties. `get_event_type` return 11 [which corresponds to](https://docs.gtk.org/gdk3/enum.EventType.html#leave_notify) `GDK_LEAVE_NOTIFY`.

Honestly in the implementation of `on_hover_lost` and `isHovered` I don't know where it's required for the hovered window to retain focus but the ags issue tracker seem to indicate it does. According to [Aylur](https://github.com/Aylur/ags/issues/221#issuecomment-1862007812) ags transitioning to gtk4 would fix this but I don't think this is done. I don't really know how this can be fixed 'properly', I don't think I'm familiar enough with GTK, GDK, GJS, nor AGS. The only solutions I can think of right now are involve delaying, polling, or increasing the padding as you mentioned, but I don't think any of these are ideal.

**Comment by MacaylaMarvelous81** [comment]
https://github.com/user-attachments/assets/d9daa090-9462-4ae4-beb6-4db14457f9dd

Tested with:
```js
setup: self => self.poll(1, () => {
    const pointer = Gdk.Display.get_default().get_default_seat().get_pointer();
    const [, x, y] = pointer.get_position();
    print(y);
})
```

Based on this I'm making the assumption that when getting the cursor position after the cursor leaves ags, it returns the cursor's last position, since the y value doesn't update past the bar. I think for the smaller y values (< 32), it's because I'm skipping over the padding by moving the cursor so quickly, so the cursor goes from inside the bar to outside of ags. This is probably what's happening in `isHovered` because it looks like it does cursor position comparisons. I'm not sure this issue can be solved by cursor position, but the only other thing I can think of is the crossing event details.. which I have no idea how to access from GJS.

**Comment by AymanLyesri** [comment]
I've changed the logic behind the hover lost, now it uses `leave-notify-event` to detect the events and only trigger if the last event have a `y` coordinate that is greater or equal to the bar height.
To test it out run:
```
update dev
```
and then restart ags : `SUPER + b`
that will make u on dev branch where the changes are made before production

here is the new logic btw
```
export default () =>
{
    return Widget.Window({
        name: `bar`, // name has to be unique
        anchor: ["top", "left", "right"],
        exclusivity: "exclusive",
        margins: emptyWorkspace.as(margin => [margin * 69, margin * 50, 0, margin * 50]),// [top, right, bottom, left]
        layer: "top",
        visible: barLock.value,
        child: Widget.EventBox({
            // on_hover_lost: () => !barLock.value ? App.closeWindow("bar") : null,
            child: Widget.CenterBox({
                class_name: emptyWorkspace.as(empty => !!empty ? "bar empty" : "bar full"),
                start_widget: Left(),
                center_widget: Center(),
                end_widget: Right(),
            }),
            setup: (self) => self.on('leave-notify-event', (self, event: Gdk.Event) =>
            {
                const [_, x, y] = event.get_root_coords();
                print(x, y)
                if (y >= 25 && !barLock.value) App.closeWindow("bar")
            })
        })

    });
}
```

**Comment by MacaylaMarvelous81** [comment]
It works a little better with the extra leeway. Even though I still sometimes skip over it I think this is the best it can be with the current version of gtk.


https://github.com/user-attachments/assets/a1d6ac2b-f2e6-4182-92d1-ae67139d16c5

**Comment by AymanLyesri** [comment]
No updates, closing this issue..
